Feature/unit tests
PabloBona/school_library pull request #7
Opened 2023-09-06 17:24 UTC by M-Anwar-Hussaini

# We have added the following features to the project.
- ✅ Create unit tests using `Rspec` for the following files:
 - `Book`
 - `Person`
 - `Teacher`
 - `Student`
 - `Classroom`
 - `Rental`
- ✅ The test files are located at `root/src/tests`.
- ✅ No linters error.
- ✅ All tests are passed.

2023-09-06 23:45 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @M-Anwar-Hussaini, @PabloBona, and @danifromecuador
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All your tests are passing :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 23:45 UTC, tresorsawasawa commented on src/tests/book_spec.rb
> +  end
- [ ] As required for the project to have tests for all the methods in all the classes, kindly ensure that you also created tests to `#add_rental` method in the `Book` class.

2023-09-06 23:45 UTC, tresorsawasawa commented on src/tests/person_spec.rb
> +  end
- [ ] As required for the project to have tests for all the methods in all the classes, kindly ensure that you also add tests to `#add_rental` method in the `Person` class.

2023-09-06 23:45 UTC, tresorsawasawa commented on src/tests/student_spec.rb
> +  end
- [ ] As required for the project to have tests for all the methods in all the classes, kindly ensure that you also add tests to `#play_hooky` method in the `Person` class.

- [ ] As required for the project to have tests for all the classes that you created while implementing the Decorator design pattern and all methods in all the classes, kindly ensure that you also add tests in the `Nameable` `TrimmerDecorator`, and `CapitalizeDecorator` and all methods inside.

2023-09-07 01:39 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @PabloBona @M-Anwar-Hussaini @danifromecuador, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 01:47 UTC, PabloBona commented
Thanks for your feedback @anagudelogu  !!

2023-09-09 04:52 UTC, merged